/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ConfigurableInterestVaultConfigInterface
  extends ethers.utils.Interface {
  functions: {
    "acceptDebt(address)": FunctionFragment;
    "fairLaunch()": FunctionFragment;
    "getFairLaunchAddr()": FunctionFragment;
    "getInterestRate(uint256,uint256)": FunctionFragment;
    "getKillBps()": FunctionFragment;
    "getReservePoolBps()": FunctionFragment;
    "getWNativeRelayer()": FunctionFragment;
    "getWrappedNativeAddr()": FunctionFragment;
    "initialize(uint256,uint256,uint256,address,address,address,address)": FunctionFragment;
    "interestModel()": FunctionFragment;
    "isWorker(address)": FunctionFragment;
    "killFactor(address,uint256)": FunctionFragment;
    "minDebtSize()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setParams(uint256,uint256,uint256,address,address,address,address)": FunctionFragment;
    "setWorkers(address[],address[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "wNativeRelayer()": FunctionFragment;
    "workFactor(address,uint256)": FunctionFragment;
    "workers(address)": FunctionFragment;
    "wrappedNative()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "acceptDebt", values: [string]): string;
  encodeFunctionData(
    functionFragment: "fairLaunch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFairLaunchAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInterestRate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getKillBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReservePoolBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWNativeRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWrappedNativeAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "interestModel",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isWorker", values: [string]): string;
  encodeFunctionData(
    functionFragment: "killFactor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minDebtSize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setParams",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setWorkers",
    values: [string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "wNativeRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "workFactor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "workers", values: [string]): string;
  encodeFunctionData(
    functionFragment: "wrappedNative",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "acceptDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fairLaunch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFairLaunchAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKillBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReservePoolBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWNativeRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWrappedNativeAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "interestModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isWorker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "killFactor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minDebtSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setParams", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setWorkers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wNativeRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "workFactor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "workers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wrappedNative",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ConfigurableInterestVaultConfig extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ConfigurableInterestVaultConfigInterface;

  functions: {
    acceptDebt(worker: string, overrides?: CallOverrides): Promise<[boolean]>;

    "acceptDebt(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    fairLaunch(overrides?: CallOverrides): Promise<[string]>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<[string]>;

    getFairLaunchAddr(overrides?: CallOverrides): Promise<[string]>;

    "getFairLaunchAddr()"(overrides?: CallOverrides): Promise<[string]>;

    getInterestRate(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getInterestRate(uint256,uint256)"(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getKillBps(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getKillBps()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getReservePoolBps(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getReservePoolBps()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getWNativeRelayer(overrides?: CallOverrides): Promise<[string]>;

    "getWNativeRelayer()"(overrides?: CallOverrides): Promise<[string]>;

    getWrappedNativeAddr(overrides?: CallOverrides): Promise<[string]>;

    "getWrappedNativeAddr()"(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    interestModel(overrides?: CallOverrides): Promise<[string]>;

    "interestModel()"(overrides?: CallOverrides): Promise<[string]>;

    isWorker(worker: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isWorker(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    killFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "killFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    minDebtSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    "minDebtSize()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    setParams(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setParams(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setWorkers(
      addrs: string[],
      configs: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setWorkers(address[],address[])"(
      addrs: string[],
      configs: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    wNativeRelayer(overrides?: CallOverrides): Promise<[string]>;

    "wNativeRelayer()"(overrides?: CallOverrides): Promise<[string]>;

    workFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "workFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    workers(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    "workers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    wrappedNative(overrides?: CallOverrides): Promise<[string]>;

    "wrappedNative()"(overrides?: CallOverrides): Promise<[string]>;
  };

  acceptDebt(worker: string, overrides?: CallOverrides): Promise<boolean>;

  "acceptDebt(address)"(
    worker: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  fairLaunch(overrides?: CallOverrides): Promise<string>;

  "fairLaunch()"(overrides?: CallOverrides): Promise<string>;

  getFairLaunchAddr(overrides?: CallOverrides): Promise<string>;

  "getFairLaunchAddr()"(overrides?: CallOverrides): Promise<string>;

  getInterestRate(
    debt: BigNumberish,
    floating: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getInterestRate(uint256,uint256)"(
    debt: BigNumberish,
    floating: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getKillBps(overrides?: CallOverrides): Promise<BigNumber>;

  "getKillBps()"(overrides?: CallOverrides): Promise<BigNumber>;

  getReservePoolBps(overrides?: CallOverrides): Promise<BigNumber>;

  "getReservePoolBps()"(overrides?: CallOverrides): Promise<BigNumber>;

  getWNativeRelayer(overrides?: CallOverrides): Promise<string>;

  "getWNativeRelayer()"(overrides?: CallOverrides): Promise<string>;

  getWrappedNativeAddr(overrides?: CallOverrides): Promise<string>;

  "getWrappedNativeAddr()"(overrides?: CallOverrides): Promise<string>;

  initialize(
    _minDebtSize: BigNumberish,
    _reservePoolBps: BigNumberish,
    _killBps: BigNumberish,
    _interestModel: string,
    _wrappedNative: string,
    _wNativeRelayer: string,
    _fairLaunch: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(uint256,uint256,uint256,address,address,address,address)"(
    _minDebtSize: BigNumberish,
    _reservePoolBps: BigNumberish,
    _killBps: BigNumberish,
    _interestModel: string,
    _wrappedNative: string,
    _wNativeRelayer: string,
    _fairLaunch: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  interestModel(overrides?: CallOverrides): Promise<string>;

  "interestModel()"(overrides?: CallOverrides): Promise<string>;

  isWorker(worker: string, overrides?: CallOverrides): Promise<boolean>;

  "isWorker(address)"(
    worker: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  killFactor(
    worker: string,
    debt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "killFactor(address,uint256)"(
    worker: string,
    debt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  minDebtSize(overrides?: CallOverrides): Promise<BigNumber>;

  "minDebtSize()"(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  setParams(
    _minDebtSize: BigNumberish,
    _reservePoolBps: BigNumberish,
    _killBps: BigNumberish,
    _interestModel: string,
    _wrappedNative: string,
    _wNativeRelayer: string,
    _fairLaunch: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setParams(uint256,uint256,uint256,address,address,address,address)"(
    _minDebtSize: BigNumberish,
    _reservePoolBps: BigNumberish,
    _killBps: BigNumberish,
    _interestModel: string,
    _wrappedNative: string,
    _wNativeRelayer: string,
    _fairLaunch: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setWorkers(
    addrs: string[],
    configs: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setWorkers(address[],address[])"(
    addrs: string[],
    configs: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  wNativeRelayer(overrides?: CallOverrides): Promise<string>;

  "wNativeRelayer()"(overrides?: CallOverrides): Promise<string>;

  workFactor(
    worker: string,
    debt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "workFactor(address,uint256)"(
    worker: string,
    debt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  workers(arg0: string, overrides?: CallOverrides): Promise<string>;

  "workers(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  wrappedNative(overrides?: CallOverrides): Promise<string>;

  "wrappedNative()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    acceptDebt(worker: string, overrides?: CallOverrides): Promise<boolean>;

    "acceptDebt(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    fairLaunch(overrides?: CallOverrides): Promise<string>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<string>;

    getFairLaunchAddr(overrides?: CallOverrides): Promise<string>;

    "getFairLaunchAddr()"(overrides?: CallOverrides): Promise<string>;

    getInterestRate(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getInterestRate(uint256,uint256)"(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getKillBps(overrides?: CallOverrides): Promise<BigNumber>;

    "getKillBps()"(overrides?: CallOverrides): Promise<BigNumber>;

    getReservePoolBps(overrides?: CallOverrides): Promise<BigNumber>;

    "getReservePoolBps()"(overrides?: CallOverrides): Promise<BigNumber>;

    getWNativeRelayer(overrides?: CallOverrides): Promise<string>;

    "getWNativeRelayer()"(overrides?: CallOverrides): Promise<string>;

    getWrappedNativeAddr(overrides?: CallOverrides): Promise<string>;

    "getWrappedNativeAddr()"(overrides?: CallOverrides): Promise<string>;

    initialize(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: CallOverrides
    ): Promise<void>;

    interestModel(overrides?: CallOverrides): Promise<string>;

    "interestModel()"(overrides?: CallOverrides): Promise<string>;

    isWorker(worker: string, overrides?: CallOverrides): Promise<boolean>;

    "isWorker(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    killFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "killFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minDebtSize(overrides?: CallOverrides): Promise<BigNumber>;

    "minDebtSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setParams(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setParams(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setWorkers(
      addrs: string[],
      configs: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setWorkers(address[],address[])"(
      addrs: string[],
      configs: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    wNativeRelayer(overrides?: CallOverrides): Promise<string>;

    "wNativeRelayer()"(overrides?: CallOverrides): Promise<string>;

    workFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "workFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    workers(arg0: string, overrides?: CallOverrides): Promise<string>;

    "workers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    wrappedNative(overrides?: CallOverrides): Promise<string>;

    "wrappedNative()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    acceptDebt(worker: string, overrides?: CallOverrides): Promise<BigNumber>;

    "acceptDebt(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fairLaunch(overrides?: CallOverrides): Promise<BigNumber>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFairLaunchAddr(overrides?: CallOverrides): Promise<BigNumber>;

    "getFairLaunchAddr()"(overrides?: CallOverrides): Promise<BigNumber>;

    getInterestRate(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getInterestRate(uint256,uint256)"(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getKillBps(overrides?: CallOverrides): Promise<BigNumber>;

    "getKillBps()"(overrides?: CallOverrides): Promise<BigNumber>;

    getReservePoolBps(overrides?: CallOverrides): Promise<BigNumber>;

    "getReservePoolBps()"(overrides?: CallOverrides): Promise<BigNumber>;

    getWNativeRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    "getWNativeRelayer()"(overrides?: CallOverrides): Promise<BigNumber>;

    getWrappedNativeAddr(overrides?: CallOverrides): Promise<BigNumber>;

    "getWrappedNativeAddr()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    interestModel(overrides?: CallOverrides): Promise<BigNumber>;

    "interestModel()"(overrides?: CallOverrides): Promise<BigNumber>;

    isWorker(worker: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isWorker(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    killFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "killFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minDebtSize(overrides?: CallOverrides): Promise<BigNumber>;

    "minDebtSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    setParams(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setParams(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setWorkers(
      addrs: string[],
      configs: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setWorkers(address[],address[])"(
      addrs: string[],
      configs: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    wNativeRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    "wNativeRelayer()"(overrides?: CallOverrides): Promise<BigNumber>;

    workFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "workFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    workers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "workers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wrappedNative(overrides?: CallOverrides): Promise<BigNumber>;

    "wrappedNative()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptDebt(
      worker: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "acceptDebt(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fairLaunch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fairLaunch()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFairLaunchAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getFairLaunchAddr()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInterestRate(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getInterestRate(uint256,uint256)"(
      debt: BigNumberish,
      floating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getKillBps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getKillBps()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getReservePoolBps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getReservePoolBps()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWNativeRelayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getWNativeRelayer()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWrappedNativeAddr(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getWrappedNativeAddr()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    interestModel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "interestModel()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isWorker(
      worker: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isWorker(address)"(
      worker: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    killFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "killFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minDebtSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "minDebtSize()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setParams(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setParams(uint256,uint256,uint256,address,address,address,address)"(
      _minDebtSize: BigNumberish,
      _reservePoolBps: BigNumberish,
      _killBps: BigNumberish,
      _interestModel: string,
      _wrappedNative: string,
      _wNativeRelayer: string,
      _fairLaunch: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setWorkers(
      addrs: string[],
      configs: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setWorkers(address[],address[])"(
      addrs: string[],
      configs: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    wNativeRelayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "wNativeRelayer()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    workFactor(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "workFactor(address,uint256)"(
      worker: string,
      debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    workers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "workers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    wrappedNative(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "wrappedNative()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
